apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgstroperator
  namespace: rgstroperator-system
  labels:
    app.kubernetes.io/name: rgstroperator
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rgstroperator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rgstroperator
    spec:
      serviceAccountName: rgstroperator
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/piqab/rgstroperator:latest
          imagePullPolicy: IfNotPresent
          command: ["/manager"]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
